# Generated by Django 2.2.5 on 2019-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='from_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consult',
            name='message',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consult',
            name='subject',
            field=models.CharField(choices=[('Feedback', 'Feedback'), ('Report a bug', 'Report a bug'), ('Feature request', 'Feature request')], default='Feedback', max_length=32),
        ),
    ]
