# Generated by Django 2.2.5 on 2019-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0002_auto_20190921_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='from_email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='consult',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
