# Generated by Django 2.2.5 on 2019-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0003_auto_20190922_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='subject',
            field=models.CharField(choices=[('Feedback', 'Feedback'), ('Report a bug', 'Report a bug'), ('Feature request', 'Feature request')], max_length=32),
        ),
    ]
