# Generated by Django 2.2.5 on 2019-09-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0004_auto_20190922_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='from_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='consult',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='consult',
            name='subject',
            field=models.CharField(choices=[('Feedback', 'Feedback'), ('Report a bug', 'Report a bug'), ('Feature request', 'Feature request')], max_length=30),
        ),
    ]
